### ISSUE TITLE
Feature: option for use "lng create" command without create a folder

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#11]
Is possible to run `lng create` without creating a folder like `com.company.app.name`?
This is for when the repository is already initialized.

**Comment by michielvandergeest** [comment]
No that's not possible. The `lng create` command is intended exclusively for creating a _new_ project.

What are you trying to achieve with the create command for an existing project?

**Comment by MattiaPontonioKineton** [comment]
@michielvandergeest other developer has created a GitLab repository. 
I've cloned that and then create a new project with the CLI. So the CLI project was inside the repository's folder. For now, I've solved merging manually the two project. Maybe this is a Git issue.
