### ISSUE TITLE
Favicon support | Control over index.html

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#15]
## Steps to reproduce
1. I'm getting an error while using the `dist` into a browser.
2. The error is related to the absense of `favicon.ico` file
3. If I put the file into the `dist` folder the issue solves
4. If I rebuild the build the `favicon.ico` went deleted and the issue went reopened

```
Failed to load resource: the server responded with a status of 403 (denied)
http://data.oscdn.any.sky.it/favicon.ico
```

More generally this issue addresses to the need of have more control over the features of the [HTML](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5) document.

**Comment by michielvandergeest** [comment]
Favicon support has been added in the latest version of the SDK (see https://github.com/WebPlatformForEmbedded/Lightning-SDK/issues/33).
Please be aware that favicons are only relevant during development in the browser.
