### ISSUE TITLE
Safe Reverse domain name notation changing

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#17]
Hello,
is safe to change the name of the folder?
For example, I need to change `com.sky.app.lightning.demo.app` to `com.skyita.lightning`.
There are other points where the CLI use this name?
Best regards

**Comment by michielvandergeest** [comment]
Yes it's safe to change the name of the folder, because Lightning-CLI commands are always run from within the project folder anyway.

Also the folder itself doesn't even need to be a reverse domain. The appId (in `metadata.json`) however _must_ be in reverse domain format.
