### ISSUE TITLE
'lng typo' displays NO error message..

### ISSUE THREAD

**Issue by FitzerIRL** [WebPlatformForEmbedded/Lightning-CLI#18]
`lng crete`  (typo of create)

Issuing the above command - just _quietly_ ignores the command.

A error message like ...

> 'lng crete' is not a recognized command.   typo ? 

... would be useful.

**Comment by michielvandergeest** [comment]
Hi @FitzerIRL that sounds like a good addition. Thanks or the suggestion. Added to the feature list.

**Comment by FitzerIRL** [comment]
Cool.  It should prompt instructions like “lng” alone does ...

👍🏻

**Comment by michielvandergeest** [comment]
Added in v1.4.0
