### ISSUE TITLE
Object doesn't support property or method 'APP_com_kineton_app_lightning_cli'

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#2]
Error:
```
0: Object doesn't support property or method 'APP_com_kineton_app_lightning_cli'
startApp.js (26,6)
```
Code:
```
const app = window[appMetadata.id](
        settings.appSettings,
        settings.platformSettings,
        settings.appData
      )
```
Browser: Microsoft Edge 44.18362.1.0
Working in Chrome.
After a check, I've found that my `appMetadata.id` that is `APP_com_kineton_app_lightning_cli` is not defined in `window` in Edge but it is in Chrome.

**Comment by michielvandergeest** [comment]
Edge is currently not one of our target browsers, I don't expect we'll be making Edge specific fixes atm.

Please note that Es5-support is in the works. An Es5 version could possibly be used to run in Edge.
