### ISSUE TITLE
[Feature] lng start

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning-CLI#37]
A command similar or equal to `lng dev` but thought to be mapped to https://docs.npmjs.com/cli/start.

**Comment by wouterlucas** [comment]
Disagree with that. Why?

**Comment by mattiapontonio** [comment]
Looking forward to write 2 flow in a readme:

- 1 for a developer that need to develop and maybe has some side-settings
- 1 for a human tester that only need ti launch the app

## My goal (for tester)
1. clone
2. install
3. start (now i map to dev)

Its Just a formalism now but should be good to keep the two experiences separate.

**Comment by michielvandergeest** [comment]
For tester the commands should then be: `lng build` followed by `lng serve`
I don't think it makes sense to create a whole new CLI command for this.
