### ISSUE TITLE
constant url

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning-CLI#39]
Is possible to make the url of dev to be constant in order to put that in a readme?
Es: http://127.0.0.1:8081/

**Comment by michielvandergeest** [comment]
No. The http-server used in the `lng serve` and `lng dev` commands looks for the first available port on localhost higher than `8080`.

This is intended (and convenient) behaviour during development, and allows a developer to serve multiple Lightning apps through the Lightning-CLI without having issues with ports in use.

If you need to have a fixed port for some reason, you are free to run any http-server in the `dist`-folder yourself and specify the port there. Optionally you can add it as an npm script to your app's package.json.

**Comment by mattiapontonio** [comment]
@michielvandergeest thanks. Is possible to evaluate to pass the port as a parameter of `lng serve`?
