### ISSUE TITLE
Watching external .mjs

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning-CLI#45]
Hello,

I've created externals `.mjs` modules for my App (for defining custom classes). 
They are not in the `src` folder. 
Can I ensure/watch these files that the apps realods in `lng dev` mode?
Maybe If I try to make them `node_modules` it will works?

**Comment by michielvandergeest** [comment]
The CLI only watches the `src` and `static` folder and `settings.json`. If you use external libraries in your app, I suggest you put them in `src/libs`.

Watching the `node modules` folder doesn't sound like a good idea for performance reasons.

**Comment by mattiapontonio** [comment]
Thanks for the support. 

I want to share my idea: 
Share `class` definitions between `node` `server` and `Lightining` Front End.

So my classes, for example `Player` may have the responsability of communicate with his REST API (CRUD his self).

So a `Player` should be instancieted or received by a `Component` (ex the `PlayerPosition`), shared between components but also manipulated by the server and even saved in a database.

I'm not thinking about external libraries but my custom business logic definition.

You think that a Front End project not have to contain custom classes but only `Components`?

Even for `Utils` functions (for example the function that find the winner) should be good if It should be shared with the server and so mantained in one place only.

I'm looking for a way to share these classes in order to be DRY...

It's reasonable?

The best thing I think is to release those definitions as modules and then import them as dependecies in both server and client projects.

Now they are in a shared folder and I'm restarting both `server` and `lng` processes mannually every time is needed.

Best regards
Mattia

**Comment by michielvandergeest** [comment]
In general it seems like a good idea to share generic code between the front-end and the backend yes.

As for the CLI rebuilding your _front-end_ project when any of these shared class definitions change, you have the following options:

- place the files inside your front-end’s `src\shared` folder (easiest, but not very semantic)
- keep the files outside of the front-end and create a symlink into your App’s `src` folder - that should also trigger a change in the watcher I believe
- restart the watch / build commands manually whenever a generic file changes

**Comment by mattiapontonio** [comment]
Thanks for the support.
I recognise that is not a CLI issue so it is closable for me.
Best regards
Mattia
