### ISSUE TITLE
Commitizen breaks ES5 builds

### ISSUE THREAD

**Issue by lewispeel** [WebPlatformForEmbedded/Lightning-CLI#46]
It seems adding a library like [Commitizen](http://commitizen.github.io/cz-cli/) or [commitLint](https://commitlint.js.org/#/) breaks ES5 applications. ES6 applications seem to be unaffected. This is the error I'm seeing when trying to launch the application;

![image](https://user-images.githubusercontent.com/1321492/79334664-9bea7d00-7f18-11ea-9d93-ed4897a1599e.png)

**Steps to reproduce**
- Create an empty project using `lng create` (eslint=yes, install npm dependencies=yes, init empty git=yes)
- Change `platformSettings/esEnv` to "es5" inside settings.json
- [Make the repo Commitizen-friendly](http://commitizen.github.io/cz-cli/#making-your-repo-commitizen-friendly)
  - `npm i commitizen -g`
  - `commitizen init cz-conventional-changelog --save-dev --save-exact`
- Run app in the browser `lng dev` and open the console in DevTools

**Comment by michielvandergeest** [comment]
Hi Lewis, thanks for your report. Just confirming I managed to reproduce the issue here. It seems like a babel has an issue with `commitizen`. I'm investigating a fix.

**Comment by lewispeel** [comment]
Further investigation revealed downgrading Commitizen from v4 to v3 works - we'll use that for now.

**Comment by michielvandergeest** [comment]
Great! I'm keeping the issue open as I can image the same issue might arise with other packages in the future.

Not sure yet though if it's something the package (like Commitizen) should fix, or that it should be solved in the Lightning-CLI.

**Comment by lewispeel** [comment]
Yeah, I initially thought it's a problem with Commitizen but the same happens with commitlint and the ES6 versions of Lightning apps are unaffected so thought it's something in the building of the ES5 app

**Comment by mattiapontonio** [comment]
https://github.com/WebPlatformForEmbedded/Lightning/issues/96

https://github.com/WebPlatformForEmbedded/Lightning-SDK/issues/25

**Comment by michielvandergeest** [comment]
The issues linked above are outdated. And also not exactly related to the issue at hand.

@lewispeel I've identified the problem in the es5 build procedure. It is indeed a babel issue related to this specific package (but possibly also others). I have a possible fix, but before I can push that I need to make sure the change doesn't introduce new issues with other packages.

**Comment by lewispeel** [comment]
Thanks for the update Michiel

**Comment by michielvandergeest** [comment]
@lewispeel I have pushed possible fix for this issue to the `fix/es5-build` branch.

If you want you can give it a go already (before it's merged into master) by installing the CLI straight from that specific branch: `npm install -g WebPlatformForEmbedded/Lightning-CLI#fix/es5-build`

**Comment by michielvandergeest** [comment]
Fix is part of v1.5.0 release.
