### ISSUE TITLE
Where to put static assets

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#5]
Proposal for documenting how it works and where to put the static assets like svg files and images in the source code.

**Comment by michielvandergeest** [comment]
We are working on improving the documentation. And we will make sure to touch on this subject better as well. Thanks for the suggestion.

In case you hadn't figured it out yourself yet: the blueprint project created by the CLI adds a `static` folder, where you can put all your static assets (you'r free to organize into subfolders). For using a graphical asset inside your code I'll refer you to the documentation on the `Utils` plugin (you can acces the SDK docs by running `lng docs` inside your project folder).
