### ISSUE TITLE
[CORS, Full-Stack Dev Enviroment] Sharing Node/Express Server with Node Server started from the CLI

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning-CLI#50]
https://github.com/WebPlatformForEmbedded/Lightning/issues/167

**Comment by mattiapontonio** [comment]
@michielvandergeest hello, can you please answer me about that?
Actually I've issues with CORS and sharing the same origin could help me fix that.
The question is about mount an express server on that same as serves the front-end or vice versa.
Now, for example, in my local enviroment I've:
- Lightning-CLI APP Front-End Server: http://127.0.0.1:8110 // port is not hardcoded
- Express server for REST API: http://127.0.0.1:3000 // port is hardcoded

Best regards
Mattia

**Comment by mattiapontonio** [comment]
Currently, I've solved with this solution but the "problem" of changing the `origin` every developing session and / or documenting that to collegues remains.
```
import cors from 'cors';
import express from 'express';
import multiplayer from './routes/multiplayer/index.mjs';
var app = express();
app.use(cors({
    credentials: true, 
    origin: 'http://127.0.0.1:8112' // TODO bisogna cambiarlo ogni volta....
}));
app.use(express.json());
app.listen(3000, () => console.log("Server running on port 3000"));
multiplayer(app);
export default app;
```

**Comment by michielvandergeest** [comment]
You are by no means required to use the `lng serve` command for launching your Lightning App frontend. It's merely offered as a convenience during development.

Feel free to fire up your own http-server and set the dist folder as root and specify a port (i.e. `http-server ./dist -p 1234`). You can even map your front-end to the dist folder within Express if you want.

Running the Lightning App does not depend on it being served through the lightning CLI.

**Comment by mattiapontonio** [comment]
@michielvandergeest thank You very much for the support.
Best regards.
Mattia
