### ISSUE TITLE
Preserve customs files in ./dist

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#6]
Actually, when You run `lng build` all added files in the `./dist` folder are cancelled.
Should be good if they are preserved in order to have the possibility to setup html files for distribution.

**Comment by michielvandergeest** [comment]
I don't think that will be a very good idea. The `dist` folder is used for creating builds mainly during development. Not clearing the dist folder upon each (fresh) build, increases the chance of false positives and other possible unexpected issues.
