### ISSUE TITLE
Connect to Lightning bundling system

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#7]
Referencing this:
https://github.com/WebPlatformForEmbedded/Lightning/issues/99
in order to suggest to provide a way to bundling features in a unified way via CLI in custom projects.
Main topic: Compatibility (es. https://babeljs.io/ features).

**Comment by michielvandergeest** [comment]
Running your Lightning App in es5 bundles is in the works and expected to be released soon.
