### ISSUE TITLE
You are using an older version of the Lightning SDk. Please consider upgrading to the latest version.

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#8]
Running `lng dev` I got this warning:
`⚠️  You are using an older version of the Lightning SDk. Please consider upgrading to the latest version.  ⚠️`
My questions are:
- Is possible to solve issue direclty updating the bootstrap created by `lng create`?
- Anyway, how to upgrade the SDK? There is a way via command line?
- If i run `npm list` i got wpe-lightning-sdk@2.0.0 (git+https://github.com/WebPlatformForEmbedded/Lightning-SDK.git#9a1480d32d1824f78466ddec924cfc112a082f41) that is higher than "1.1.3" from current SDK release. It sound strange, probably a npm issue.

Best regards,
Mattia

**Comment by michielvandergeest** [comment]
This is a temporary issue related to the SDK 2.0.0 not officially being released yet. You can safely ignore this warning for now, until 2.0.0.

Or in case you don't want to wait you can install the latest version (rc) directly off the #next branch (https://github.com/WebPlatformForEmbedded/Lightning-SDK/tree/next). But beware that we haven't been applying version numbers for each change yet.

**Comment by MattiaPontonioKineton** [comment]
@michielvandergeest 
The warning came back today.
As I can see now the more recent tag of `wpe-lightning-sdk` is `2.1.0`.
https://github.com/WebPlatformForEmbedded/Lightning-SDK/tree/2.1.0
May I ask to document the process to update or expose a method via CLI as a next feature?
